### ISSUE TITLE
java.net.UnknownHostException: user-manager.9019.dbs.backbase.test: No address associated with hostname

### ISSUE THREAD

**Issue by eliasnogueira** [Backbase/bb-fuel#136]
### Description
When the user runs the basic data setup [1] an exception is thrown:
```java
java.net.UnknownHostException: user-manager.9019.dbs.backbase.test: No address associated with hostname
```

### Possible cause
The `application-k8s.yml` has changed on the `user` service, where they were updated to the lean version, but it's not ready yet on the regular environment creation.

### Possible solution
We must revert back the changes for the `user` service, where the new values should be:
```yml
bb-fuel:
  dbs:
    user: http://user.${environment.name}.${environment.domain}/client-api
  dbs-service-names:
    user: user-presentation-service
```

### Additional information
It happens in the latest version.
A possible workaround is to use the `2.6.13`
