### ISSUE TITLE
Update the k8s-beta application file with lean services

### ISSUE THREAD

**Issue by eliasnogueira** [Backbase/bb-fuel#147]
## The problem
The current `application-k8s-beta.yml` profile has the triangular version for the remaining services that should be on lean.

## Action
Replace the following services by the following lean reference

```yaml
  dbs-service-names:
    accessgroup: access-control
    actions: action-service
    arrangements: arrangements-manager
    billpay: billpay-integrator
    legalentity: access-control
    limits: limit
    messages: messages-service
    notifications: notifications-service
    payments: payment-order-service
    pfm: transaction-category-collector
    user: user-manager
    products: arrangement-manager
```
